<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>ID Match</h1>
        <div>
            <p style="color:red;">Это AI fintech API.</p>
            <p>
                Система принимет изображение лица и изображение пасспорта (айди карты) человека, а на выходе выдает следующую информацию:<br>
                <span style="color:blue;">процент матчинга лица на пасспорте</span>,
                <span style="color:green;">распознанный текст с пасспорта</span>
            </p>
        </div>
    </body>
</html>
