<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>NEW ID Match</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="./dist/styles.css">
    </head>
    <body>
        <h1>ID Match</h1>
        <div>
            <p style="color:red;">Это AI fintech API.</p>
            <p>
                Система принимет изображение лица и изображение пасспорта (айди карты) человека, а на выходе выдает следующую информацию:<br>
                <span style="color:blue;">процент матчинга лица на пасспорте</span>,
                <span style="color:green;">распознанный текст с пасспорта</span>
            </p>
            <p style="color:black;margin-top: 50px;">Давайте проверим как это работает</p>
            <p style="margin-top:30px;">
                <form method="POST" action="/" enctype="multipart/form-data">
                    <label>Загрузите вашу фотографию:</label>
                    <input type="file" name="face">
                    <p></p>
                    <label>Загрузите скан вашего пасспорта:</label>
                    <input type="file" name="id">
                    <p></p>
                    <button type="submit">Отправить в ИИ</button>
                </form>
            </p>

            <p>
                <?php if (isset($outPic)) : ?>
                    <img src="/images/<?= htmlspecialchars($outPicF); ?>">
                    <br><br>
                    <img src="/images/<?= htmlspecialchars($outPic); ?>">
                <?php endif; ?>
            </p>

        </div>
    </body>
</html>
