<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=0">
        <meta name="format-detection" content="telephone=no">

        <title>NEW ID Match</title>
        <link rel="stylesheet" href="./dist/styles.css">
    </head>
    <body>
        <header>
            <section>
                <div class="menu">
                    <a href="/" class="logotype">
                        <svg xmlns="http://www.w3.org/2000/svg" width="36" href="26d" viewBox="0 0 36 26"><defs><style>.cls-1{fill:#fff;}</style></defs><title>logo_id</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><polygon class="cls-1" points="0 26 9.36 26 14.4 0 5.04 0 0 26"/><path class="cls-1" d="M23,0H17V26h6v-.08A13.06,13.06,0,0,0,36,13,13.06,13.06,0,0,0,23,0Z"/></g></g></svg>
                        IDMatch
                    </a>
                    <ul class="munu-wrap">
                        <li class="menu-wrap--item">
                            <a href="#contacts">Контакты</a>
                        </li>
                    </ul>
                </div>
                <h1>
                    Это AI fintech API
                </h1>
            </section>
        </header>
        <main>
            
        </main>
        <footer id="contacts">

        </footer>




        <h1>ID Match</h1>
        <div>
            <p style="color:red;">Это AI fintech API.</p>
            <p>
                Система принимет изображение лица и изображение пасспорта (айди карты) человека, а на выходе выдает следующую информацию:<br>
                <span style="color:blue;">процент матчинга лица на пасспорте</span>,
                <span style="color:green;">распознанный текст с пасспорта</span>
            </p>
            <p style="color:black;margin-top: 50px;">Давайте проверим как это работает</p>
            <p style="margin-top:30px;">
                <form method="POST" action="/" enctype="multipart/form-data">
                    <label>Загрузите вашу фотографию:</label>
                    <input type="file" name="face">
                    <p></p>
                    <label>Загрузите скан вашего пасспорта:</label>
                    <input type="file" name="id">
                    <p></p>
                    <button type="submit">Отправить в ИИ</button>
                </form>
            </p>

            <p>
                <?php if (isset($outPic)) : ?>
                    <img src="/images/<?= htmlspecialchars($outPicF); ?>">
                    <br><br>
                    <img src="/images/<?= htmlspecialchars($outPic); ?>">
                <?php endif; ?>
            </p>

        </div>
    </body>
</html>
